### ISSUE TITLE
Inconsistent Pulling Of A Channels Videos

### ISSUE THREAD

**Issue by CheekyBellend** [RandomUser99/TwitchVods#4]
Hey, firstly would like to say thank you for this wonderful service as it makes it so much easier to watch older twitch vods.  However i have noticed an issue with regards to the pulling of older videos on the channel DansGaming.

Often it will pull all of his videos, but then other times it will only pull a limited number making it impossible to resume where you left off if the video you were watching is older than the date it decided to stop pulling videos past.

Would be grateful if this was able to be fixed.

**Comment by skulblakka** [comment]
I noticed this too. I think the issue here is that we are doing to many API requests with channels with a long VOD history causing the Twitch API to deny our request. 

If I noticed correctly the application will crash (or at least exit) if this happens. As the applications seems to always overwrite the previously created pages, you will end up with a page missing the older videos.

**Comment by RandomUser99** [comment]
I thought I had fixed this issue previously by using the Polly library to add a wait and retry policy when the API request threw an exception.  It's not an issue with the amount of API requests that are being made. It just seems to be that the the twitch API throws an exception on occasion.

I've tweaked the retry policy slightly to handle any exceptions and upped the retry count from 5 to 10 in  my latest commit.

I'll leave this issue open for now. Let me know if it improves or if the problem persists.

**Comment by skulblakka** [comment]
>I thought I had fixed this issue previously by using the Polly library to add a wait and retry policy when the API request threw an exception

I had been running bd4c722 the whole time so if that was changed afterwards it might just be because my version was outdated. 

I have pulled the newest version now and will check if the issue appears again.
